const actualQuotes = [
    "Now, while this day is yours,make full use of it. \n- Ralph Marston",
    "Do, think, dream, feel, with everything you are. Life is yours today, and well worth all you can give. \n- Ralph Marston",
    "Make the best choice, not just the easiest choice. \n- Ralph Marston",
    "Tell yourself something good, and let that goodness come to life through you. \n- Ralph Marston",
    "Yes, there will be difficulties. Yes, you can succeed anyway. \n- Ralph Marston",
    "Pick a specific path, act on it, and transform your choice into real value. \n- Ralph Marston",
    "It's always your choice what you hold on to inside. Each time, each day, choose only the best. \n- Ralph Marston",
    "Dream, dream, dream it until you do it. The dream again and pull all of life higher along with you. \n- Ralph Marston",
    "Today you have time, energy, opportunity that you'll never have again. Do something great with it. \n- Ralph Marston",
    "Let every passing day deepen your enjoyment and appreciation of life. \n- Ralph Marston",
    "The point of this day is to make new progress and enrich all of life. Get to the point and get it done. \n- Ralph Marsten",
    "Encourage yourself to create a vision, right now, of the ideal way this day can unfold for you. \n- Ralph Marsten",
    "Let go of any hesitation to act. Transform today from opportunity to achievement. \n- Ralph Marsten",
    "Let the power of peace take you higher than any conflict ever could. \n- Ralph Marsten",
    "There is no need to rush. You have this beautiful day to experience as all its greatest treasures unfold. \n- Ralph Marsten",
    "Let your highest vision guide you and inspire you. Let objective facts inform you and instruct you. \n- Ralph Marsten",
    "Getting rid of what's working poorly can leave you with nothing that works at all. See if you can find a way to improve rather than just destroy.",
    "Now is when life can begin to be the best you can imagine. \n- Ralph Marsten",
    "Gently take a few steps away. Arrive at a place where you can focus on what is truly important. \n- Ralph Marsten",
    "Be thankful, and reap the full benefit of good fortune that's been coming your way longer than you can imagine. \n- Ralph Marsten",
    "If you're going to make a positive difference, then get with it, now. Your intention is clear, and your time is here, so go for it. \n- Ralph Marsten",
    "Of course you should fight fire with fire. You should fight *everything* with fire. \n- Jaya Ballard",
    "We are shaped by our thoughts; we become what we think. When the mind is pure, joy follows like a shadow that never leaves. \n- Gautama Buddha",
    "You, yourself, as much as anybody in the entire universe, deserve your love and affection.\n- Gautama Buddha",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.\n- Gautama Buddha",
    "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.\n- Gautama Buddha",
    "We are what we think. All that we are arises with our thoughts. With our thoughts, we make the world.\n- Gautama Buddha",
    "Peace comes from within. Do not seek it without.\n- Gautama Buddha",
    "You only lose what you cling to.\n- Gautama Buddha",

]

module.exports = actualQuotes;