const actualQuotes = [
    "Now, while this day is yours, make full use of it. \n- Ralph Marston",
    "Do, think, dream, feel, with everything you are. Life is yours today, and well worth all you can give. \n- Ralph Marston",
    "Make the best choice, not just the easiest choice. \n- Ralph Marston",
    "Tell yourself something good, and let that goodness come to life through you. \n- Ralph Marston",
    "Yes, there will be difficulties. Yes, you can succeed anyway. \n- Ralph Marston",
    "Pick a specific path, act on it, and transform your choice into real value. \n- Ralph Marston",
    "It's always your choice what you hold on to inside. Each time, each day, choose only the best. \n- Ralph Marston",
    "Dream, dream, dream it until you do it. The dream again and pull all of life higher along with you. \n- Ralph Marston",
    "Today you have time, energy, opportunity that you'll never have again. Do something great with it. \n- Ralph Marston",
    "Let every passing day deepen your enjoyment and appreciation of life. \n- Ralph Marston",
    "The point of this day is to make new progress and enrich all of life. Get to the point and get it done. \n- Ralph Marsten",
    "Encourage yourself to create a vision, right now, of the ideal way this day can unfold for you. \n- Ralph Marsten",
    "Let go of any hesitation to act. Transform today from opportunity to achievement. \n- Ralph Marsten",
    "Let the power of peace take you higher than any conflict ever could. \n- Ralph Marsten",
    "There is no need to rush. You have this beautiful day to experience as all its greatest treasures unfold. \n- Ralph Marsten",
    "Let your highest vision guide you and inspire you. Let objective facts inform you and instruct you. \n- Ralph Marsten",
    "Getting rid of what's working poorly can leave you with nothing that works at all. See if you can find a way to improve rather than just destroy. \n- Ralph Marsten",
    "Now is when life can begin to be the best you can imagine. \n- Ralph Marsten",
    "Gently take a few steps away. Arrive at a place where you can focus on what is truly important. \n- Ralph Marsten",
    "Be thankful, and reap the full benefit of good fortune that's been coming your way longer than you can imagine. \n- Ralph Marsten",
    "If you're going to make a positive difference, then get with it, now. Your intention is clear, and your time is here, so go for it. \n- Ralph Marsten",
    "Of course you should fight fire with fire. You should fight *everything* with fire. \n- Jaya Ballard",
    "We are shaped by our thoughts; we become what we think. When the mind is pure, joy follows like a shadow that never leaves. \n- Gautama Buddha",
    "You, yourself, as much as anybody in the entire universe, deserve your love and affection.\n- Gautama Buddha",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.\n- Gautama Buddha",
    "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.\n- Gautama Buddha",
    "We are what we think. All that we are arises with our thoughts. With our thoughts, we make the world.\n- Gautama Buddha",
    "Peace comes from within. Do not seek it without.\n- Gautama Buddha",
    "You only lose what you cling to.\n- Gautama Buddha",
    "When I'm around you, I kind of feel like I'm on drugs. Not that I do drugs. Unless you do drugs, in which case I do them all the time. All of them. \n- Scott Pilgrim",
    "I know you play mysterious and aloof just to avoid getting hurt. And I know you have reasons for not wanting talk about your past. I want you to know that I don't care about any of that stuff. Because I'm in lesbians with you. \n- Scott Pilgrim",
    "Bread makes you fat? \n- Scott Pilgrim",
    "Knives Chau: I've never even kissed a guy before.\n\nScott Pilgrim: Hey... me neither.",
    "Stacey Pilgrim: Did you really see a future with this girl?\n\nScott Pilgrim: Like... with jet-packs?",
    "Scott Pilgrim: You once were a ve-gone, but now you will begone.\n\nTodd Ingram: Ve-gone?",
    "Wallace Wells: Guess who's drunk!\nScott Pilgrim: I guess Wallace.\nWallace Wells: You guess right!",
    "Envy Adams: You are incorrigible. \n\nTodd Ingram: I don't know the meaning of the word. \n\n(He really doesn't.)",
    "Envy Adams: Short answer: Vegans are just better then everyone else.",
    "Do, or do not. There is no try. \n- Yoda",
    "Sing us a song, you're the piano man, sing us a song tonight. \n\n'Cause we're all in the mood for a melody, and you've got us feeling all right \n- Billy Joel",
    "'Cause they're sharing a drink they call loneliness, but it's better than drinking alone. \n- Billy Joel",
    "If you're going through hell, keep going. \n- Winston Churchill",
    "Never, never, never give up. \n- Winston Churchill",
    "We make a living by what we get, but we make a life by what we give. \n- Winston Churchill",
    "Success consists of going from failure to failure without loss of enthusiasm. \n- Winston Churchill",
    "History is written by the victors. \n- Winston Churchill",
    "Never give in, never give in, never, never, never, never—in nothing, great or small, large or petty—never give in except to convictions of honor and good sense.\n- Winston Churchill",
    "A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty. \n- Winston Churchill",
    "Never in the field of human conflict was so much owed by so many to so few.\n- Winston Churchill",
    "If you can fill the unforgiving minute \n With sixty seconds’ worth of distance run,\nYours is the Earth and everything that’s in it,\n And—which is more—your adulthood is won!\n\n- Rudyard Kipling \n(w/ gender neutral edit found on google)",
    "The path of the righteous man is beset on all sides by the iniquities of the selfish and the tyranny of evil men. Blessed is he, who in the name of charity and good will, shepherds the weak through the valley of darkness, for he is truly his brother’s keeper and the finder of lost children. And I will strike down upon thee with great vengeance and furious anger those who would attempt to poison and destroy my brothers. And you will know my name is the Lord when I lay my vengeance upon thee. \n\n-Pulp Fiction",
    "It is no measure of health to be well adjusted to a profoundly sick society. \n- Jiddu Krishnamurti (h/t Reuben)",
    "Ph'nglui mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn \n- H.P. Lovecraft (for Plague)",
    "There was a young lady named Bright \nWhose speed was far faster than light \nShe set out one day \nIn a relative way \n And returned on the previous night. \n\n- A. H. Reginald Buller (h/t Kelly)",
    "My name is Harrison. \n\n- Harrison",
    "Your parents haven't given you the bang chat yet? \nAnd *now* I start the recording\n\n-Harrison",
    "Just make a digital bookshelf.\n\n- Harrison",
    "Make a Brad Simulator.\n\n- Harrison",
    "What it does is it whips the <div> out at the last second \n\n- Ross Jourdain",
    "Rupert: I think I would travel back in time to when I was eating my breakfast, that was awesome.\n\nCliff: ... I've got good news for you, mate.",
    "IT'S A TRAP!! \n\n- Admiral Ackbar (h/t Riki)",
    "Time to hit the dusty trail. \n\n- Dan",
    "He aha te mea nui o te ao? He tangata, he tangata, he tangata. \n\nWhat is the most important thing in the world? It is people, it is people, it is people. \n\n- Maori Proverb",
    "Pierce: [raising a glass] To the empowerage of words.\n\nJeff: To the irony of that sentence.\n\n- Community",
    "Jeff: Hey, Troy sneezes like a girl! \n\nTroy: And how 'bout I pound you like a boy! That didn't come out right.\n\n- Community",
    "Nobody knows it, but I've got secret screen, something something only for me.",
    "People tend to overestimate what they can do in a short amount of time and underestimate what they can do in even a slightly longer time. \n\n- Stanley Roache \n(Bill Gates and Tony Robbins have said something similar, but this more awesome version appears to be a Roache original)",
    "When in mortal danger, \nWhen beset by doubt, \nRun in little circles, \nWave your arms and shout. \n- Sandy Mitchell"

]

module.exports = actualQuotes;